import React from 'react'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
const Layout = ({children,title='flagi'}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<header className={styles.header}>
  logo
</header>
      <main className={styles.main}>
        {children}
      </main>

      <footer className={styles.footer}>
      <a href="https://www.youtube.com/watch?v=v8o9iJU5hEA&t=4535s" target='blank'>ссылка на урок</a>
      </footer>
    </div>
  )
}

export default Layout
